version: '3.8'
services:
  monitor:
    image: inzania/network-traffic-metrics:latest
    network_mode: host
    environment:
      - "NTM_INTERFACE=enp5s0"
      - "NTM_FILTERS=(src net 192.168.1.0/24 and dst net 192.168.1.0/24)"

  prometheus:
    image: prom/prometheus:main
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - "monitor:192.168.1.110"


  grafana:
    image: grafana/grafana:6.6.2
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    links:
      - "prometheus:prometheus"
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"


volumes:
  prometheus-data:
  grafana-data:
